=== PetarNRT55/ist2021/proizvodi.dtd
<!ELEMENT Proizvodi (Proizvod)+>
<!ELEMENT Proizvod (Kategorija, Cena, TekstOglasa, Oznake, Akcija)>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ELEMENT TekstOglasa (#PCDATA)>
<!ELEMENT Oznake (Oznaka)*>
<!ELEMENT Oznaka (#PCDATA)>
<!ELEMENT Akcija EMPTY>
<!ATTLIST Kategorija kategorija (maticne|ram|procesori|graficke) #REQUIRED>
<!ATTLIST Cena valuta (eur|rsd) "rsd">
<!ATTLIST Akcija cena CDATA #IMPLIED>
<!ATTLIST Akcija datumIsteka CDATA #IMPLIED>
<!-- 
U fajlu proizvodi.xml kreirati podatke o Proizvodima u veb prodavnici. Proizvod je opisan sledećim elementima:

Kategorija proizvoda – sadrži obavezno jednu od
predefinisanih kategorija (npr. laptopovi, monitori, stolovi, stolice…)

Cena – iznos. Cena je dodatno opisana atributom valuta koji
podrazumevano označava dinare. 

Tekst oglasa – isključivo tekstualni sadržaj bez umetnutih
elemenata. 

Oznaka (tag) oglasa – jedan proizvod može imati više
oznaka. Oznaka bliže opisuje proizvod i nema ograničen
skup vrednosti. Oznake nisu u hijerarhijskoj relaciji
međusobno. 

Akcija proizvoda –Akcija je dodatno opisana atributom
cena ako je na akciji koliko sada iznosi njegova cena. Takođe ima atribut datum isteka do kada važi akcija.
Jedan proizvod na akciji može biti više puta i svaki put
imati drugu cenu. 
-->

=== PetarNRT55/ist2021/proizvodi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Proizvodi SYSTEM "proizvodi.dtd">
<!-- 
U fajlu proizvodi.xml kreirati podatke o Proizvodima u veb prodavnici. Proizvod je opisan sledećim elementima:

Kategorija proizvoda – sadrži obavezno jednu od
predefinisanih kategorija (npr. laptopovi, monitori, stolovi, stolice…)

Cena – iznos. Cena je dodatno opisana atributom valuta koji
podrazumevano označava dinare. 

Tekst oglasa – isključivo tekstualni sadržaj bez umetnutih
elemenata. 

Oznaka (tag) oglasa – jedan proizvod može imati više
oznaka. Oznaka bliže opisuje proizvod i nema ograničen
skup vrednosti. Oznake nisu u hijerarhijskoj relaciji
međusobno. 

Akcija proizvoda –Akcija je dodatno opisana atributom
cena ako je na akciji koliko sada iznosi njegova cena. Takođe ima atribut datum isteka do kada važi akcija.
Jedan proizvod na akciji može biti više puta i svaki put
imati drugu cenu.
 -->
<Proizvodi>
    <Proizvod>
        <Kategorija kategorija="graficke">Graficke Kartice</Kategorija>
        <Cena valuta="rsd">29990</Cena>
        <TekstOglasa>GTX 1660 super 6gb</TekstOglasa>
        <Oznake>
            <Oznaka>4</Oznaka>
        </Oznake>
        <Akcija cena="24990" datumIsteka="02.10.2021"></Akcija>
    </Proizvod>
    <Proizvod>
        <Kategorija kategorija="procesori">Procesori</Kategorija>
        <Cena>23490</Cena>
        <TekstOglasa>AMD Ryzen 5 3600</TekstOglasa>
        <Oznake>
            <Oznaka>2</Oznaka>
        </Oznake>
        <Akcija></Akcija>
    </Proizvod>
    <Proizvod>
        <Kategorija kategorija="maticne">Maticne Ploce</Kategorija>
        <Cena valuta="rsd">21990</Cena>
        <TekstOglasa>MSI B550 TOMAHAWK</TekstOglasa>
        <Oznake>
            <Oznaka>1</Oznaka>
        </Oznake>
        <Akcija cena="20490" datumIsteka="5.10.2021"></Akcija>
    </Proizvod>
</Proizvodi>
